### ISSUE TITLE
getCommentReplies: Error: length(url) == 1 is not TRUE

### ISSUE THREAD

**Issue by marvinmilatz** [pablobarbera/Rfacebook#101]
Hi Pablo, 

thanks for the amazing package that will help to make Swiss journalism stronger. 

I've been experiencing a problem with the getCommentReplies function. The console returns: Error: could not find function "getCommentReplies". Unfortunately, I haven't found any info on the internet yet. 

Looking forward to hearing from you. All the best, 

Marvin

Here's my session info, if this is any help: 

R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.12.2 (unknown)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rfacebook_0.6.6 httpuv_1.3.3    rjson_0.2.15    httr_1.2.1     

loaded via a namespace (and not attached):
[1] R6_2.2.0    tools_3.2.4 curl_2.3    Rcpp_0.12.8

**Comment by yanturgeon** [comment]
Hi Marvin,

I think the code is not implemented in the package yet. Copy/paste the code on this page (https://github.com/pablobarbera/Rfacebook/blob/master/Rfacebook/R/getCommentReplies.R) in your script before to run the getCommentReplies function and it should work.

Yan T.

**Comment by marvinmilatz** [comment]
Hi Yan,

thanks for the swift reply. I just updated my R version to 3.3.1 (2016-06-21) – now, R detects the function. However, now the error is:  Error: length(url) == 1 is not TRUE

Actually, the same happens, when I run the function code from the Github link you shared. Any ideas? 

New session info:

R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.12.2 (Sierra)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rfacebook_0.6.11 httpuv_1.3.3     rjson_0.2.15     httr_1.2.1      

loaded via a namespace (and not attached):
[1] R6_2.2.0    tools_3.3.1 Rcpp_0.12.8

**Comment by yanturgeon** [comment]
Hi Marvin,

Do you have comments in your database? It may be the problem...

Here's my script to fetch the post (level 1) then the comments (level 2) then the replies (level 3) : https://github.com/yanturgeon/R_Script/blob/master/getCommentReplies_dev.R

The fonction getCommentReplies is implemented in the script.

@pablobarbera may have a better answer ;)

Yan

**Comment by marvinmilatz** [comment]
Hi Yan,

thanks so much, your script is awesome. 

Have a nice day,

Marvin
