### ISSUE TITLE
getPost

### ISSUE THREAD

**Issue by paeselhz** [pablobarbera/Rfacebook#106]
I was wondering when I extract the data from a public post, I get information about likes and comments, there's any way that I could get information about shares too? Not only the count of it...

Thanks in advance

**Comment by pablobarbera** [comment]
Unfortunately it's not possible to get that information, at least as far as I know. There's a "sharedposts" endpoint in the API, but that returns only the list of users who shared a post AND have granted permission to use your application. So in practice it's not very useful... Sorry.
