### ISSUE TITLE
getUsers function throwing an error

### ISSUE THREAD

**Issue by khansrk** [pablobarbera/Rfacebook#108]
I am using getUsers() function to get the info of the specific user 

my code is 

you <- getUsers("80471929*******", token=fb_oauth,private_info = FALSE)

my error is

Error in callAPI(query, token) : 
  (#100) Tried accessing nonexisting field (first_name) on node type (Page)

please help me out

**Comment by engti** [comment]
I'm facing the same issue. Looks like, either, in some cases people don't put a first name in their FB profile which makes it throw an error, or the user Id is actually for a page and it doesnt have a valid first name field.

**Comment by khansrk** [comment]
Is there a way to solve this problem

**Comment by engti** [comment]
Use the callAPI function. Something like this:

    ## define the url to call and the fields, in param add in the fields you'd want
    host = "https://graph.facebook.com/v2.8/"
    param = "?fields=name"  
    ## fetch the data
    url <- paste0(host,_userID_,param)
    data <- callAPI(url,token)

**Comment by khansrk** [comment]
thanks @engti
