### ISSUE TITLE
searchPages function seem to be not working towards Korean search string

### ISSUE THREAD

**Issue by statkclee** [pablobarbera/Rfacebook#109]
SearchPages function retrieves facebook pages successfully, but when I enter Korean strings like "이재명", "손학규", "문재인" etc, searchPages retrieves odd pages or pages not associated with search strings.

NOTE: "이재명", "손학규", "문재인" <- they are very famous Korean politicians.

$ ljm_page <- searchPages("이재명", token=fb_oauth, n = 10)
$ ljm_page %>% dplyr::select(id, name, likes, link, category)

                 id                        name     likes                                       link           category
1      320511193884                    Facebook 184907862    https://www.facebook.com/FacebookKorea/    Product/Service
2   673283106147611             5-Minute Crafts  22007614      https://www.facebook.com/5min.crafts/ Media/News Company
3   205249152839914 National Geographic Channel  58501431      https://www.facebook.com/NatGeoKorea/         TV Channel
4        6815841748                Barack Obama  54508678      https://www.facebook.com/barackobama/         Politician
5        8245623462                         NBA  32407136              https://www.facebook.com/nba/      Sports League
6   171020899583505                      손학규      6708        https://www.facebook.com/koreasohn/         Politician
7        5330548481                    Maroon 5  39315550          https://www.facebook.com/maroon5/      Musician/Band
8  1614251518827491                       Tasty  81850382    https://www.facebook.com/buzzfeedtasty/ Media/News Company
9      156794164312                Harry Potter  75425088 https://www.facebook.com/harrypottermovie/              Movie
10     228735667216                    BBC News  38968328          https://www.facebook.com/bbcnews/ Media/News Company

**Comment by pablobarbera** [comment]
@statkclee So weird, it seems to work for me:

```{r}
> page <- searchPages("이재명", token=token, n = 10)
> page %>% dplyr::select(id, name, category)
                 id                                   name               category
1   164179696957459                        이재명의 페이지    Government Official
2  1456755394547871                                 이재명               Interest
3   752770898223423                        이재명은 합니다 Political Organization
4   206639936468308                         Bassist 이재명               Musician
5  1260507914013776                     이재명대전충남연대                  Cause
6   143083936227811          이재명과 더불어 10만 권리당원              Community
7   368374240173904                      이재명의 바른세상           Record Label
8  1016679688447622                                 이재명             Politician
9  1819948194917632 이재명과 새로운 대한민국 - 부산#손가혁              Community
10 1064927933606000                     가자 이재명과 함께          Public Figure
```

Maybe you want to experiment with the encoding? Do you get the same results when you try through the graph API explorer [here](https://developers.facebook.com/tools/explorer/?method=GET&path=search%3Fq%3D%22%EC%9D%B4%EC%9E%AC%EB%AA%85%22%26type%3Dpage&version=v2.9) ?
