### ISSUE TITLE
Creating token version 1.0 to query the API

### ISSUE THREAD

**Issue by kbarnes171** [pablobarbera/Rfacebook#110]
As stated in the documentation for the GetUsers function: _"Note that these fields will ONLY be returned for friends and when the version of the token that is used to query the API is 1.0. For other users, they will be NA, even if they are visible on Facebook via web."_ 

I'm not sure if it is possible to create a v1.0 of the token, or if that 1.0 refers to the API version. If so, will it ever be possible to revert to v1.0?

Unfortunately, I specifically need access to the aforementioned fields. I am friends with the profiles I am running GetUsers function on.

Apologies if this is not the correct place for posting this.

**Comment by mpiccirilli** [comment]
@kbarnes171 The 1.0 version of the API was unavailable after April 30, 2015.  See the Changelog: https://developers.facebook.com/docs/apps/changelog
