### ISSUE TITLE
Is it possible to retrieve events from a page? getEvents?

### ISSUE THREAD

**Issue by jp1312** [pablobarbera/Rfacebook#112]
Hi,
congrats, your package is amazing!
I was wondering if there is a function to retrieve events given a page ID, in the same way as we retrieve posts given a page ID. 
Thanks,
Jacopo

**Comment by pablobarbera** [comment]
Not at the moment, but from a quick look at the API, it looks like this is something that could be accessed easily. I'll try to add a new function in the next couple of weeks when I find some free time. In the meantime, you can use callAPI() to make the API requests.

**Comment by pablobarbera** [comment]
@jp1312 More like a couple months, but it's now in Rfacebook :-)
