### ISSUE TITLE
Pagination does not work if api argument is not NULL

### ISSUE THREAD

**Issue by kasperwelbers** [pablobarbera/Rfacebook#115]
Specifically, I encountered this error when using getPage with n > 25 and api = '2.6'.

The url for the next page (content$paging$`next`) already contains the API version, which results in an error if callAPI adds it a second time. My simple fix was to make sure the api argument in callAPI is NULL if callAPI is within a pagination loop, but perhaps fixing this within callAPI is more elegant.

**Comment by pablobarbera** [comment]
Great suggestion! Thanks @kasperwelbers
