### ISSUE TITLE
getUsers returns Error

### ISSUE THREAD

**Issue by raulmilan** [pablobarbera/Rfacebook#116]
Hi Pablo,

more in love than ever with your wonderful package. 

I extracted the ids of several people, and I now want to get some basic information about the people.

So I made a vector users with the respective 500 ids from "from_id" and used getUsers.

userinterested = getUsers(users = users, token = token)

R starts getting the info

 24 users -- 50 users -- 75 users -- 94 users -- 119 users -- 146 users -- 172 users -- 202 users -- 236 users -- 263 users -- 292 users -- 330 users -- 355 users -- 376 users -- 399 users -- 426 users -- 455 users -- 481 users -- 487 users -- 491 users -- 495 users -- 496 users -- 497 users -- 498 users -- 499 users -- 

Then I get the following error message:

Error in which(unlist(lapply(content, function(x) is.null(x$category)))) : 
  argument to 'which' is not logical

Anything I can do about this?

Many thanks beforehand for your kind help!

Raoul

**Comment by pablobarbera** [comment]
@raulmilan Sorry for the slow reply. I'm finally getting to fix all the issues. I wasn't able to replicate this error, but I got rid of the "category" variable, which is the one that seemed to be causing the error here (it's not available for users anymore, as far as I can tell).

**Comment by danielcarter** [comment]
Any update on this? I'm running into the same problem:

test = getUsers(ids, token=token)

Error in which(unlist(lapply(content, function(x) is.null(x$category)))) : 
  argument to 'which' is not logical
