### ISSUE TITLE
New version of API and problem with fbOAuth

### ISSUE THREAD

**Issue by josefslerka** [pablobarbera/Rfacebook#117]
Hi, yesterday Facebook switch to new API and it seems that callAPI has problem with fbOAuth.  New token is return via JSON. Quick fix is just remove type = "application/x-www-form-urlencoded" from fbOauth.

**Comment by rubenpeciv** [comment]
Thank you @josefslerka! The fix worked well for me.

**Comment by johnataylor13** [comment]
Hi @josefslerka - I'm running into the same issue.  I'm trying to get the token through R (RFacebook) - where does one type in that quick fix?  Thanks!

John

**Comment by josefslerka** [comment]
Like this https://gist.github.com/josefslerka/db21dc50f286ddf341b1d5f048612a9d

**Comment by johnataylor13** [comment]
Wow!  Thanks so much.  Seems to be working great.

**Comment by javob** [comment]
Thank you!

**Comment by ElaineSuh** [comment]
Hello~~, 

I used to use the below codes to get the token until 2days ago, but it doesn't work anymore. 
I still get the authentication complete, but I get the error: Error in callAPI(url = url, token = token) : 
  An access token is required to request this resource.
Any way to fix in a simple way? 
I tried to understand the codes from the link above, but it is too difficult for me. 
token <- fbOAuth(app_id="123456789", app_secret="4aa2aa543d464860684",
                 extended_permissions = FALSE,
                 legacy_permissions = FALSE)
After I get the token, I use getpage.

**Comment by javob** [comment]
ElaineSuh, 

Download josefslerka's .R file from his link: https://gist.github.com/josefslerka/db21dc50f286ddf341b1d5f048612a9d

Then run that code to create a new version of the function fbOAuth. 

Then re run your code:

token <- fbOAuth(app_id="123456789", app_secret="4aa2aa543d464860684",
extended_permissions = FALSE,
legacy_permissions = FALSE)

It worked for me.

**Comment by ElaineSuh** [comment]
Oh~~~~ Yes. It did work!!! Thank you so much!!

**Comment by adlihs** [comment]
Excellent...  Thanks for the solution!

**Comment by josefslerka** [comment]
You welcome...:)
