### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by khodijahhaddad** [pablobarbera/Rfacebook#118]
Hello! I've tried to use Rfacebook package at R following your instructions. Everything is ok until the very last step when I found this:

"Waiting for authentication in browser...

Press Esc/Ctrl + C to abort

Authentication complete.

Error in curl::curl_fetch_memory(url, handle = handle) :

Problem with the SSL CA cert (path? access rights?)"

Could you help me? I don't know how to fix it :S

**Comment by pablobarbera** [comment]
Hi @khodijahhaddad See the discussion in #126. Maybe try also with the most recent version of Rfacebook on github? I fixed some login issues there as well.
