### ISSUE TITLE
Error installing github version

### ISSUE THREAD

**Issue by BroVic** [pablobarbera/Rfacebook#119]
Hi. I tried installing the package with **devtools** and this is the error I got:

> Error: Does not appear to be an R package (no DESCRIPTION)

**Comment by josefslerka** [comment]
Please, can put here copy of r commands used for installation?

**Comment by BroVic** [comment]
Thanks for the response. It's

`devtools::install_github("pablobarbera/Rfacebook")`

Cheers!

**Comment by josefslerka** [comment]
devtools::install_github("pablobarbera/Rfacebook/Rfacebook") works

**Comment by BroVic** [comment]
Yup, like a charm. Thanks!
