### ISSUE TITLE
Retrieve comments for multiple Posts

### ISSUE THREAD

**Issue by rayms** [pablobarbera/Rfacebook#122]
I am using getPost to retrieve comments for posts, but is there anyway to do so for all posts? 

The example provided is: 

getPost(post=page$id[#], token, n = 500, comments = TRUE), where # is the specific id of the Post. 

Is there anyway to retrieve comments for all Posts without having to iterate through each id of a Post.

**Comment by pablobarbera** [comment]
@rayms Unfortunately, not with the current version of Rfacebook. You could try building your own API call and use `callAPI()` but I would recommend against it, because generally it will be too much data for a single call.
