### ISSUE TITLE
getPage - params 'since' and 'until' no longer valid

### ISSUE THREAD

**Issue by rodik** [pablobarbera/Rfacebook#124]
There were some changes to the Facebook API and I can only use 'since' and 'until' params for the pages i manage. Using them on other public pages returns:

`{ 
  "data": [
  ]
}`

example API call:
`10513336322/posts?fields=message,created_time,link,from&limit=25&since=2016/01/01&until=2017/01/05`

removing the time filters will work

**Comment by kevin0932** [comment]
Hi, did you figure out how the Facebook API changed? I used to retrieve many posts (thousands until a date) from a specific facebook page. However, just several days ago I found that I can only retrieve much fewer posts than before. I don't know what happened and still get lost. 

Would you please share any information that you figured out? Many thanks!

**Comment by kevin0932** [comment]
Oh, something to add: when I now use the function getPage() with no time filter, I can normally get several hundreds of posts and they are in two clearly separated time ranges, for example, some old posts created before 10/12/2009 and the rests are between 10/04/2017-today 01/05/2017.

**Comment by rodik** [comment]
Hey kevin, you will find more information on this [bug report](https://developers.facebook.com/bugs/389409684792879). Looks like it's a temporary issue.
I have also tried providing 'since' and 'until' params as POSIX time. Doesn't work.
Providing no 'since' and 'until' params will work but will only get you the last couple of weeks of data.

**Comment by kevin0932** [comment]
Hi @rodik , Thanks a lot for your information 👍
