### ISSUE TITLE
Issues with token

### ISSUE THREAD

**Issue by vivek14632** [pablobarbera/Rfacebook#125]
> fb_oauth <- fbOAuth(app_id="*******",app_secret="******")
Copy and paste into Site URL on Facebook App Settings: http://localhost:1410/ 
When done, press any key to continue...
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
> fb_page <- getPage(page="subway", token=fb_oauth,n=10,feed = T,reactions = T)
**Error in callAPI(url = url, token = token) : 
  An access token is required to request this resource.**

Noted: I have put '*' instead of credentials for the security reasons.

**Comment by ThomasWilli** [comment]
I got the same problem. Modifying the url within getPage.R did the job for me:

    url <- paste0('https://graph.facebook.com/',page,'/posts?fields=from,message,created_time,type,link,story,comments.summary(true)',',likes.summary(true),shares')

to

    url <- paste0('https://graph.facebook.com/',page,'/posts?fields=from,message,created_time,type,link,story,comments.summary(true)',',likes.summary(true),shares&access_token=', YOURTOKEN)

Maybe that could be updated?
Best,
Tom

**Comment by ThomasWilli** [comment]
I do have the same problem. `getPost` does work, but `getPage` is somehow broken... I tried to figure out why but I fail modyfing the original function.

**Comment by elliothimmelfarb** [comment]
I am also having the exact same issue

**Comment by vivek14632** [comment]
Here is one solution i found which is working for me.

Get an app token following this URL: https://developers.facebook.com/tools/explorer

In Application box, select your app and click on 'Get token' and select 'Get App token'. You will get your token. Use the following code to get page. 


new_token<-"YOUR NEW TOKEN"
getPage(page='page_name', token=toString(new_token),n=100,feed = T,reactions = T)
