### ISSUE TITLE
searchGroup only limited to n = 25?

### ISSUE THREAD

**Issue by josephuses** [pablobarbera/Rfacebook#128]
Can we let `searchGroup` return more than 25 groups?

**Comment by josephuses** [comment]
There are hidden characters in the file. Leaving 

`lxml`
`pyquery`

worked for me.

**Comment by pablobarbera** [comment]
Thank you, good idea!

**Comment by holnburger** [comment]
Somehow I get an error using this function with "n=100" (or other numbers of course): 

`search_groups <- searchGroup("AfD", token)` works fine, whereas `search_groups <- searchGroup("AfD", token, n=100)` returns:

```
Fehler in as.vector(x, "character") : 
  cannot coerce type 'environment' to vector of type 'character'
```
