### ISSUE TITLE
getNetwork in Rfacebook is giving an error

### ISSUE THREAD

**Issue by spykeburn** [pablobarbera/Rfacebook#13]
Hi,
The getNetwork function is giving an error:
The command- mat <- getNetwork(token, format="adj.matrix")
Error in callAPI(query, token) : 
  (#12) user/mutual_friends is deprecated for versions v2.0 and higher

I know that facebook has changed its API which is causing this error. Have anybody figured out any workaround for this? Please a little help is appreciated.

Thanks.

**Comment by johnnoelvictorino** [comment]
Hi, I've updated the query line based on your recommendation. It seems to work for me
