### ISSUE TITLE
unauthorized token

### ISSUE THREAD

**Issue by nandita-gupta** [pablobarbera/Rfacebook#132]
I am trying to fetch likes and posts from my friends profile to analyze the personality. but i am getting this error.

userlikes <- getLikes(*******, token, n = 1)

Error in getLikes(*********, token, n = 1) : 
User not found, or token is not authorized.

Can anybody help/guide?

--Nandita

**Comment by pablobarbera** [comment]
@nandita-gupta Unfortunately this information is no longer available through the API. You can only get the list of likes for the authenticated user. I have updated the documentation to make this point clear.
