### ISSUE TITLE
Unable to retrieve Reactions

### ISSUE THREAD

**Issue by cbailiss** [pablobarbera/Rfacebook#134]
Hello there
Thanks for the useful package.  I am unable to retrieve reactions for a FB page I am an admin on.
Calling:
`page <- getPage(pageId, token, n=25, reactions=TRUE)`
returns:
Error in callAPI(url = url, token = token, api = api) : 
  (#12) Reactions read API requires version v2.6 or higher
Trying (and the same with api='2.6'):
`page <- getPage(pageId, token, n=25, reactions=TRUE, api='2.9')`
returns:
Error in callAPI(url = url, token = token, api = api) : 
  Unknown path components: /7950759473/posts
Am I doing something wrong?  Sorry if so.  
I am using the current version on CRAN (0.6.15).
The call to getPage succeeds with reactions=FALSE.
The same errors happen when calling getReactions directly.
Thanks
Chris

**Comment by pablobarbera** [comment]
Try with`api="v2.9"` . I will add a note to the documentation or fix the function so that it also recognizes `2.9` or similar. Thanks!

**Comment by cbailiss** [comment]
Thanks for the quick response.  Will try this on Monday and report back.

**Comment by cbailiss** [comment]
Retested with v2.9 instead of just 2.9 and works as expected.  Thanks again.

**Comment by sapinet2018** [comment]
Hi Team ,

I am getting similar error but am using the API version 2.12.

kindly advise.
