### ISSUE TITLE
Feature request: List of group members

### ISSUE THREAD

**Issue by kumarhk** [pablobarbera/Rfacebook#137]
Thanks for creating this invaluable tool! I was wondering if it would be possible to implement a function that would get the list of members of a Facebook group? I see that this is possible in the Facebook API: https://developers.facebook.com/docs/graph-api/reference/v2.9/group/members

**Comment by pablobarbera** [comment]
@kumarhk It seems like you need to be an admin for the group in order to be able to access the list of members to the API, no? I'm not an admin, so it would be hard for me to "blindly" write the function, but I'll leave the issue open in case someone else can help!

**Comment by yanturgeon** [comment]
@kumarhk you don't need a specific function to do it. Simply go on the https://developers.facebook.com/tools/explorer and write the code below in the get window   group_id/members?fields=id,name,administrator&limit=5000

**Comment by pablobarbera** [comment]
Thanks to @yanturgeon now there's a function called getMembers() that does this!

**Comment by kumarhk** [comment]
Thanks so much @pablobarbera and @yanturgeon!

**Comment by yanturgeon** [comment]
Hi Pablo and mastin8,

I've upgrade the code of getMembers so we can retrieve more than 5000
members, but I'm unable to make de change in github. How should I proceed?

Anyway, here is the new code:

#Should be added to the file utils.R

memberDataToDF <- function(user_data, private_info){
>   df <- data.frame(
>     name = unlistWithNA(user_data, 'name'),
>     first_name = unlistWithNA(user_data, 'first_name'),
>     last_name = unlistWithNA(user_data, 'last_name'),
>     id = unlistWithNA(user_data, 'id'),
>     administrator = unlistWithNA(user_data, 'administrator'),
>     stringsAsFactors=F)
>   return(df)
> }
>

#New getMembers.R code

getMembers <- function(group_id, token, n=5000, api=NULL){
>     url <- paste0('https://graph.facebook.com/', group_id,
>
> '/members?fields=id,name,first_name,last_name,administrator&limit=', n)
>     # making query
>   content <- callAPI(url=url, token=token)
>
>  #if no data, return error message
>   if (length(content$data)==0){
>     message("No groups with this name were found.")
>   }
>   # if data, return a data frame
>   df <- memberDataToDF(content$data)
>   while (!is.null(content$paging$`next`)){
>     query <- content$paging$`next`
>     content <- callAPI(query, token)
>     if (length(content$data)>0){
>       df <- rbind(df, memberDataToDF(content$data))
>     }
>   }
>   #return(df) #do not return group ID
>   return(cbind(df,group_id)) #return group ID on each row
> }


Yan Turgeon
PhD Student

2017-09-18 14:33 GMT-04:00 mastin8 <notifications@github.com>:

**Comment by mastin8** [comment]
Nice :) I wanted to propose something very similar for the same problem. I post it here:

# First of all I removed the n value, because to get to the limit the function has to take the first 5000
>  
> getMembers2 <- function (group_id, token, api = NULL) 
> {
> 
# This part does not change
>  
> url <- paste0("https://graph.facebook.com/", group_id, "/members?fields=id,name,first_name,last_name,administrator&limit=5000")
>   
> content <- callAPI(url = url, token = token)
>  
> if (length(content$data) == 0) {
>  
> message("No groups with this name were found.")
>  
> return(data.frame()) 
> }
>  
# This part does not change
>  
> df <- data.frame(name = unlist(lapply(content$data, "[[", 
> "name")), first_name = unlist(lapply(content$data, "[[", 
> "first_name")), last_name = unlist(lapply(content$data, 
> "[[", "last_name")), id = unlist(lapply(content$data,
> "[[", "id")), administrator = unlist(lapply(content$data, 
> "[[", "administrator")), stringsAsFactors = F)
>  
# Now I put a while to see if the output reached the limit or not. If not, I call the code asked by the Facebook API graph and I put the "token" useful to get the next record which is in content$paging$cursors$after. Then I create a df2 with new record and I do a rbind with the previous results. 
>  
> 
> while(length(content$data)== 4999 | length(content$data)== 5000) {
>  
> url <- paste0("https://graph.facebook.com/", group_id, "/members?pretty=0&fields=id,name,first_name,last_name,administrator&limit=5000&after=", content$paging$cursors$after)
>  
> 
> content <- callAPI(url = url, token = fboauth)
>  
> 
> df2 <- data.frame(name = unlist(lapply(content$data, "[[", 
>                      "name")), first_name = unlist(lapply(content$data, "[[", 
>                      "first_name")), last_name = unlist(lapply(content$data, 
>                      "[[", "last_name")), id = unlist(lapply(content$data, 
>                      "[[", "id")), administrator = unlist(lapply(content$data, 
>                      "[[", "administrator")), stringsAsFactors = F)
>  
> df <- rbind.data.frame(df,df2)
>   }
>  
> return(df)
> }
