### ISSUE TITLE
getUsers fails with "nonexisting field error"

### ISSUE THREAD

**Issue by alanault** [pablobarbera/Rfacebook#138]
Hi Pablo,

This morning, getUsers has started failing with the following error:
Error in callAPI(query, token) : 
  (#100) Tried accessing nonexisting field (first_name) on node type (Page)

Possibly this is due to Facebook deprecating one of the APIs in the last couple of days - it looks like the underlying code uses V2.0 rather than whereas I think the oldest now is v2.4

Let me know if I can help with anything

Best
Alan

**Comment by Owen-S** [comment]
Looks like some of the fields have been renamed as users and pages were split. See the following:

- https://stackoverflow.com/questions/31569567/how-can-i-get-fan-page-likes-count-using-graph-api
- https://developers.facebook.com/docs/graph-api/reference/page/
- https://developers.facebook.com/docs/graph-api/reference/user/

**Comment by pablobarbera** [comment]
Thanks @alanault @Owen-S ! This should be fixed now in the GitHub version, soon in CRAN.

**Comment by alanault** [comment]
Fantastic - thanks for the quick update!
