### ISSUE TITLE
eventDatatoDF function in getEvents()

### ISSUE THREAD

**Issue by kumarhk** [pablobarbera/Rfacebook#142]
Hi Pablo and others,

I'm working on a project where I want to examine lists of events beyond the latest 25. I know this functionality is available in some other functions such as getPage and getMembers, and I am trying to rewrite the code for getEvents to implement this. However, I am running into a problem where my updated code can't run because it can't find the function eventDatatoDF(), which is in the original code for getEvents. Could you advise on what this function is and how to use it? I'm a bit lost here.

Thanks so so much for this wonderful package!

**Comment by pablobarbera** [comment]
Hi @kumarhk -- see [here](https://github.com/pablobarbera/Rfacebook/blob/master/Rfacebook/R/utils.R#L330). All the other functions you'll need (callAPI, unlistwithNA, etc) are in utils.R as well. Please report back on your progress! :)
