### ISSUE TITLE
getPost no longer returns a likes data.frame

### ISSUE THREAD

**Issue by nlch** [pablobarbera/Rfacebook#167]
Hi @pablobarbera ,

I've been using the getPost() function this week and I've noticed that it no longer returns a likes data.frame.

Small example:
```
page <- getPage(page = "nytimes", token = in_token, n = 100, reactions = F)
id = page$id[which(page$likes_count==max(page$likes_count))]
max(page$likes_count)
post <- getPost(post = id, token = in_token, n = 100)

```

I'm using the most recent github version. I tried the version in the repositories and then the code throws the error mentioned in a couple of recent open issues (Error in while (n.l < n.likes & length(content$data) > 0 & !is.null(url <- content$paging$`next`)) { : argument is of length zero).
Am I correct in assuming this is just a temporal fix to have a working function until the error with likes is resolved?

**Comment by andreamamprin** [comment]
Hi @nlch.

It seems that Facebook has begun to authorize this edge only to page owners.
 
From Graph Api Reference: "On February 5th, 2018, User information will not be included in responses unless you make the request with a Page access token. This only applies to Comments on Pages and Posts on Pages."

https://developers.facebook.com/docs/graph-api/reference/v2.12/object/reactions

**Comment by BroVic** [comment]
In my own case with the same error, I am admin of the page. However, what I noticed was that the error is thrown by a particular post that had highest number of "likes" (> 500)...

**Comment by BroVic** [comment]
In my own case, I had the same error with `getPost()` from a Page of which I am an admin. I noticed that it was thrown be a post that had `>500` likes. Upon upwardly adjusting the function's `n` argument to 1000, the function worked properly.

**Comment by nlch** [comment]
Nothing to do here but hope Facebook re-authorizes access again then.
Thanks for the info :)
