### ISSUE TITLE
 (#190) This method must be called with a Page Access Token

### ISSUE THREAD

**Issue by diegocgaona** [pablobarbera/Rfacebook#174]
I'm having a error when I try to get data:
```
Error in callAPI(url = x, token = token) : 
  (#190) This method must be called with a Page Access Token
```
The process of creation of the token is OK, but when I try to access the API data, I receive this error (i'm using the last official version of RFacebook.)

I followed the tutorial (it worked until now): http://thinktostart.com/analyzing-facebook-with-r/

And used:
```
fb_oauth <- fbOAuth(app_id="XXXXXXXXXX", app_secret="XXXXXXXXXXXXXX", extended_permissions = T)
save(fb_oauth, file="fb_oauth")
load("fb_oauth") 
```

Then I try to get data, example:
```
fb_page_fans <- tail(getInsights(object_id = fbpage_id, token = fb_oauth, metric = c('page_fans'), 
                                  period = c('lifetime')), n = 1)
```
And get the error above... The app is already configured with localhost too.

Any idea? I think I need to create a different token, a Page Token, but I don't know how.

**Comment by anankeman** [comment]
I'm experiencing the same error. It asks me for page access token, but I use the temporary token because the fb_oauth isn't working for a while.

**Comment by adrauc** [comment]
Yes, Facebook had some changes. Can be fixed:
-Go to the dashboard of your app
-left: click on "Facbook Login" -> Settings
-Now paste in the file "Valid OAuth redirect URIs" http://localhost:1410/
-fbOAuth() should now work again in R again

**Comment by diegocgaona** [comment]
Hi @adrauc !

Thanks! I already did that (because FB show a message about the change in redirect) before I opened the issue. I tried it and other changes, but without success.
Here is my config, any other option is wrong?

![image](https://user-images.githubusercontent.com/9142126/37113711-ea09e406-2224-11e8-814f-8b27e73c5ded.png)

**Comment by anankeman** [comment]
@diegocgaona you sould use getPageToken instead fb_oauth.
Try:

`token <- getPageToken("yourpage", fb_oauth)
fb_page_fans <- tail(getInsights(object_id = fbpage_id, token = token, metric = c('page_fans'), 
                                  period = c('lifetime')), n = 1)
`

**Comment by diegocgaona** [comment]
Many thanks @anankeman ! Worked fine for me, I hope it will help the others.

**Comment by diegocgaona** [comment]
@setegonz sorry, i'm not using it anymore. Probably is something with the permissions or API version, Facebook was making my life hard too, changing the API and the access...

**Comment by setegonz** [comment]
> @setegonz sorry, i'm not using it anymore. Probably is something with the permissions or API version, Facebook was making my life hard too, changing the API and the access...

Sem problemas. Obrigado!
