### ISSUE TITLE
searchPages return error

### ISSUE THREAD

**Issue by luanamarinho** [pablobarbera/Rfacebook#188]
Hi all!

My app was approved, I'm using a temporary token, but I can't get results for the following command:
`pages <- searchPages(string="facebook", token=fb_oauth, n=100)`

Message:
0 pages Error in searchPages(string = "facebook", token = fb_oauth, n = 100) : 
 No public page mentioning the string were found

Any ideas why it's not working?

Cheers!

**Comment by setegonz** [comment]
@luanamarinho Hi! I want to use the Rfacebook package to improve my R programming skills. I have some questions about the app review process. Did you follow a tutorial or something? What kind of permissions did you ask for?


*Nao sou brasileiro... mas se quiser pode escrever em portugues. Obrigado!

**Comment by luanamarinho** [comment]
@setegonz Hi! I believe this feature is unfortunately deprecated now (since the version 2.0 of the API). You can email me at luana.marinho@gmail.com. Cheers!
