### ISSUE TITLE
Rfacebook having problems with 'Get'?!

### ISSUE THREAD

**Issue by AlexKJ** [pablobarbera/Rfacebook#20]
Hi Pablo - thanks for all your support over the Christmas period. I have just fired up RFacebook again and have the problem below:

getUsers("xyz", fb_oauth, private_info = TRUE)
Error in make_request("get", hu$handle, hu$url, config) : 
  attempt to apply non-function

Any idea what this means?

A

Edit; here are the issues I have: 

![image](https://cloud.githubusercontent.com/assets/8641631/5663125/b2106cfa-973a-11e4-9b83-f1719f3107bc.png)

**Comment by mpiccirilli** [comment]
I can't reproduce this issue.  Have you re-installed the package directly from GitHub?

**Comment by AlexKJ** [comment]
I have, yes.

**Comment by mpiccirilli** [comment]
For the getUsers function, are you using either a user id number or "me"?

**Comment by AlexKJ** [comment]
I've tried both, and reinstalled everything!

It still gives me the 'error':

1: package ‘Rfacebook’ was built under R version 3.1.2
2: package ‘httr’ was built under R version 3.1.2
3: package ‘rjson’ was built under R version 3.1.2

Alex

**Comment by mpiccirilli** [comment]
@AlexKJ it looks like you need to install a newer version of R.
