### ISSUE TITLE
searchFacebook still not working...

### ISSUE THREAD

**Issue by rhythmgupta** [pablobarbera/Rfacebook#21]
Hi Pablo,
The searchFacebook is not working for version 2.0 or higher. When will this problem be resolved ? And if not how can we generate access token for version 1.0 ?

**Comment by pablobarbera** [comment]
Hi @rhythmgupta,
Unfortunately Facebook does not allow access to public post search anymore after version 2.0 of their API, so there's nothing I can do to fix it. And it is not possible to generate access tokens for version 1.0 any longer for the same reason. Sorry.

**Comment by rhythmgupta** [comment]
Hi,
Could you please suggest some other method in R to search public posts from Facebook. And if not R then could you please some other method by which I can fetch public posts from facebook either paid or free?
