### ISSUE TITLE
Search public posts from facebook for v2.0 or higher

### ISSUE THREAD

**Issue by rhythmgupta** [pablobarbera/Rfacebook#22]
Hi Pablo,
This is in continuation to my previous issue #21 to which you commented that facebook has withdrawn access to public post search; I just want to ask on thing. 
Could you please suggest some other method in R to search public posts from Facebook. And if not R then could you please some other method by which I can fetch public posts from facebook either paid or free?
Thanks

**Comment by mammask** [comment]
Did you find any solution with this? I would be very interested to integrate R with Facebook API v 2 +  using a permanent authentication token.

**Comment by pablobarbera** [comment]
@mammask The current version of Rfacebook should allow you to create a long-lived oauth token that works with version 2.x of the API. Anything that is not available through the API (such as public posts) will not be available through Rfacebook either. There are multiple resellers of public Facebook data offering this type of access, but at a price (e.g. GNIP: https://gnip.com/sources/facebook/).
