### ISSUE TITLE
Only friends who use the application will be returned

### ISSUE THREAD

**Issue by nandex7** [pablobarbera/Rfacebook#23]
Hi.

Please could you help me why just got 9 connections. Do I have some configuration to make on facebook before doing this.?

Only friends who use the application will be returned
> my_friends <- getFriends(token, simplify = TRUE)
Only friends who use the application will be returned
See ?getFriends for more details
Thanks.
Regards.
Fernando.

**Comment by nandex7** [comment]
Hi Pablo.

Sorry I didn't read this before.
Unfortunately, with v2.0 of the API, you can only access the list of friends who are also using the same application you used to create the token (I'm assuming the Graph API Explorer). The full list of friends is no longer available through the API.

So There is another way to get the complete list  to make a getNetwork? 
Regards.
Fernando.

**Comment by caiomsouza** [comment]
Hi Pablo and Fernando,

Is there any way to get the complete list to make a getNetwork?

I just have 13 friends.

I tried to use netvizz but it does not work anymore.

How can a download my friends to put on gephi?

Thanks

**Comment by kurina** [comment]
Hi,
I am a pretty new in the R... but ...what is the meaning about this restriction from FB API 2.0 about list of friends of the authenticated user? Have some one any idea how to get a full list of friends of user (which is already fully and correctly authenticated via token) ?

thanks

Tibor
