### ISSUE TITLE
Rfacebook & Initial Redirection not working.

### ISSUE THREAD

**Issue by tapanmishra** [pablobarbera/Rfacebook#27]
I have added the app and pasted the localhost link in Add Platform. 
First time it ran and pop up an authorization browser. I gave access. 
Then when it traverse to the next time (after i press enter), it throws me the following error
Error in withCallingHandlers
object   '.rcpp_warning_recorder not found. 

And the browser redirects to - https://www.facebook.com/dialog/oauth?client_id=851698071540016&scope=user_friends,user_birthday,user_hometown,user_location,user_relationships,%20friends_birthday,friends_hometown,friends_location,friends_relationships,publish_actions,%20user_status,user_checkins,friends_status,friends_checkins,user_likes,friends_likes,read_stream,export_stream&redirect_uri=http://localhost:1410/&response_type=code&state=88K6M2Gbvg#_=_

But it says connection problem. 

I think what is happenning is as the code does not traverse, it is not creating a localhost server. But i dont know How to fix this issue.

**Comment by IronistM** [comment]
Not really an answer but regarding the "`Error in withCallingHandlers
object '.rcpp_warning_recorder not found.`" you will need to update the `Rcpp` package.

**Comment by edusuro** [comment]
Hi,
I am having a similar issue as tapanmishra.  When I run the fbOAuth function, I get redirected to a page which shows the following error:
"Invalid Scopes: friends_birthday, friends_hometown, friends_location, friends_relationships, user_checkins, friends_status, friends_checkins, friends_likes, export_stream. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions"
after clicking "OK" on the pop-up box with the error, I then get the message "Authentication complete. Please close this page and return to R."

However, when I return to R, it only shows Authentication Complete (missing Authentication Successful).  This prevents the authentication from working and it doesn't recognize my token.

Any help will be greatly appreciated

**Comment by tokumotion** [comment]
Hi, 

It seems that since FB changed again his API, Rfacebook is unable to create a "permanent" token because it automatically asks for permissions that are not available anymore. That's what happened to @edusuro as well as it happened to me.

Can the developers change the OAuth code to match the new dimensions we are allowed to have access to? So we don't have that error message.

Thanks

**Comment by pablobarbera** [comment]
Fixed now. Note that using extended_permissions=FALSE also fixed this issue. I will be pushing the changes to CRAN soon too. Thanks for reporting this!

**Comment by meggievh** [comment]
I get the same error: Invalid Scopes: read_stream. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

It works when I use  extended_permissions = FALSE, but I get no information returned aside from "me"

Thanks!!

**Comment by pablobarbera** [comment]
@meggievh thanks for your comment! You're right, it appears new Apps require Facebook's approval before you can get the data (ugh), so I changed the default in this function to extended_permissions=FALSE.

**Comment by XJERL** [comment]
But the point is that there's no data when one changes the extended... to FALSE, at least with me. So it is useless without data.

**Comment by tokumotion** [comment]
@XJERL Hi Jorge, unless you have an approved app with the permissions for extended data.

You can use the temporal token you get from Graph Explorer and work with that, you get most of the data from that temporal token.

**Comment by windrago** [comment]
thx @tokumotion!  How do you get a temporal token?

**Comment by XJERL** [comment]
Hi Pablo, I did'n know you developed the package, congrats!!! Do you speak spanish?
So it seems, then, I must get Facebook approval before I get my data.
I'll check your documentation, and look towards the temp token with Graph Explorer, do you have any suggestion?
Thnx in advance.
