### ISSUE TITLE
Issue with period='day', n=15

### ISSUE THREAD

**Issue by chipoglesby** [pablobarbera/Rfacebook#28]
Is there a reason that the period of time counts forward instead of backwards when using period='day', n=15?
 	metric_name	period	values	end_time
1	page_stories	day	42	2015-04-12T07:00:00+0000
2	page_stories	day	25	2015-04-13T07:00:00+0000
3	page_stories	day	14	2015-04-14T07:00:00+0000
4	page_stories	day	14	2015-04-15T07:00:00+0000
5	page_stories	day	14	2015-04-16T07:00:00+0000
6	page_stories	day	7	2015-04-17T07:00:00+0000
7	page_stories	day	0	2015-04-18T07:00:00+0000
8	page_stories	day	0	2015-04-19T07:00:00+0000
9	page_stories	day	0	2015-04-20T07:00:00+0000
10	page_stories	day	0	2015-04-21T07:00:00+0000
11	page_stories	day	0	2015-04-22T07:00:00+0000
12	page_stories	day	0	2015-04-23T07:00:00+0000
13	page_stories	day	0	2015-04-24T07:00:00+0000
14	page_stories	day	0	2015-04-25T07:00:00+0000
15	page_stories	day	0	2015-04-26T07:00:00+0000

Thank you for fixing getInsights!

**Comment by pablobarbera** [comment]
Thanks for reporting this! getInsights should now return the periods going back in time, and in the right order.
