### ISSUE TITLE
getLikes gives 'operator is invalid for atomic vectors' error

### ISSUE THREAD

**Issue by rjdio** [pablobarbera/Rfacebook#31]
Hi Pablo,

When i run
getLikes('pagename', token)
I get
Error in content$likes$data : $ operator is invalid for atomic vectors

Do you know what's going on here?

Thanks
Felipe

**Comment by dromney** [comment]
I am getting the same error.

**Comment by pablobarbera** [comment]
Sorry for my slow reply to this. getLikes only returns likes for a given user (and with the new API, actually only with your own account), e.g.:

getLikes("me", token=token)

I improved the documentation of this function to make it clear.

Thanks!
