### ISSUE TITLE
¿Can i still get my friend network?

### ISSUE THREAD

**Issue by hydrosIII** [pablobarbera/Rfacebook#33]
I have read that facebook made some api changes on the 30 of april, after researching for a while i found 
http://thepoliticsofsystems.net/2015/01/the-end-of-netvizz/

So, im not sure that with this R library i cant do it still.... Can i? What version of the facebook API does it uses. I was actually using the get net plugin  made for SNA course.

Do you have some comments about this?

**Comment by pablobarbera** [comment]
Unfortunately, you cannot get your entire network of friends with Rfacebook either (only the list of friends who are using the app to which the authentication token belongs). See ?getNetwork for more details.
