### ISSUE TITLE
Problem In Pulling Data From Facebook Into R

### ISSUE THREAD

**Issue by upchair** [pablobarbera/Rfacebook#36]
Dear Pablo.

I have been trying to pull data from facebook into R using the Rfacebook package but I keep getting the following error
"Error in callAPI(url = url, token = token) : 
  An unexpected error has occurred. Please retry your request later."

I switched to  using  a temporary authentication token when I started having issues with the permanent token again (which had issues initially and then you advised me to include the "extended_permissions=FALSE" parameter  in the fbOAuth command which I did and it worked fine for a while until a few days ago).

In switching to the temporary authentication token it pulled data for a few posts into R  from FB  before given me the error above. 

Please what could the problem B as I have just 2 days left to meet a deadline.

Thanks for your usual and appreciated attention.

**Comment by pablobarbera** [comment]
@upchair could you share the code that gives you this error? Everything works fine for me, so I'm not sure what the problem could be.

**Comment by upchair** [comment]
Pablo Hi.

I had to break down what  I imported into smaller batches ( based on your advice in an earlier post you gave some other people who had the same problem earlier this year when you said their seems to be a problem with the FB Graph API) and that helped a lot so in addition I had to reduce the  'n' parameter in the getpage() command from 100,000 to less than 10,000 and periodically varied this figure to between 1000-10,000 depending on the number of FB posts to be imported during each run. The frequency of the error diminished considerably when I made these adjustments.

 The code is as follows.........................................................................



channel<-odbcConnect("From R to MySQL", uid = "root", pwd = "simplex66")

#load ("fb_oauth")

token <- "CAAHGvSVKJdkBADQqZBJOOMIPgLcprKqXnUtZAocgE8K5OAQZBwcksAaFRNk3WCiHpBuZASWPl8sMZBLiXTPTFsRoRRCKcXicHcWTwcBucatY1Hw6GxXpZCFgPg8jTyj1E3XZB6aN74wbeBq777vp9DmZClEQCOFs5sOmhHicQjqXwYpWAG2OkQCidfUL5Q8YU1kZD"


#fb_page_no_nullz<-getPage(page="gtbank", token=fb_oauth,n=100000,feed=TRUE)  #Extract THE LATEST n=7 FCMB posts excluding Null rows from FCMB page# into variable/vector fb_page .

fb_page_no_nullz<-getPage(page="firstbankofnigeria", token=token, n=1000, since='2011/01/01', until='2011/12/31', feed=TRUE)  #Extract THE LATEST n=7 FCMB posts excluding Null rows from FCMB page# into variable/vector fb_page .

no_of_rows= nrow(fb_page_no_nullz)   # Count the number of rows without NULLS and store in var no_of_rows


sqlSave(channel,fb_page_no_nullz, safer=TRUE, append=TRUE, fast=TRUE) # Save The Latest n=7 FCMB Posts Extracted from The FCMB Page On Facebook To The MYSQL Table "fb_page_no_null"



odbcClose(channel)

**Comment by pablobarbera** [comment]
I just tried this now and it works for me. I guess my advice if you keep having trouble is to do the query by month instead than by year, so that the number of API calls each time you run the function is lower (I suspect the problem is that some of the API calls are failing). Sorry I cannot help more than this!

**Comment by upchair** [comment]
Pablo Hi,

Thanks for your suggestions I will take your advice and break it down further. Thank you for your help. I really appreciate it.

Richard.
