### ISSUE TITLE
Error: Deprecated: supply token object to config directly

### ISSUE THREAD

**Issue by Kenshura** [pablobarbera/Rfacebook#38]
Hello, 

First of all, thank you very much for the package. However I got an issue when i try to get my token. The first time I use it, I got this log :

fb_oauth <- fbOAuth(app_id="Myid", app_secret="myid",extended_permissions = TRUE)
Copy and paste into Site URL on Facebook App Settings: http://localhost:1410 
When done, press any key to continue...
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error: Deprecated: supply token object to config directly

When I try to type again the fbOAuth, nothing happens except the last line : Error: Deprecated: supply token object to config directly

Facebook confirmed it was ok on mybrowser and I set the localhost in my application setting. I didnt see anyone having the same issue but me. Did I do something wrong ?

**Comment by pablobarbera** [comment]
Thanks for reporting this! Looks like a problem with httr. What version of the package are you using? I'm traveling at the moment, but I will look into this asap. (In the meantime, temp authentication should still work, so hopefully you can use that for now!)






On Sunday, Jun 28, 2015 at 10:11 AM, Kenshura <notifications@github.com>, wrote:

Hello, 


First of all, thank you very much for the package. However I got an issue when i try to get my token. The first time I use it, I got this log :


fb_oauth <- fbOAuth(app_id="Myid", app_secret="myid",extended_permissions = TRUE)

Copy and paste into Site URL on Facebook App Settings: http://localhost:1410 

When done, press any key to continue...

Waiting for authentication in browser...

Press Esc/Ctrl + C to abort

Authentication complete.

Error: Deprecated: supply token object to config directly


When I try to type again the fbOAuth, nothing happens except the last line : Error: Deprecated: supply token object to config directly


Facebook confirmed it was ok on mybrowser and I set the localhost in my application setting. I didnt see anyone having the same issue but me. Did I do something wrong ?

**Comment by Kenshura** [comment]
Thank you for the quick answer. I am using the version 0.5 of rFacebook.And you are right, the temp authentification still works.

**Comment by torrentpien** [comment]
I meet the same problem.

**Comment by pablobarbera** [comment]
Yes, there's an issue with the latest version of httr, which Rfacebook uses to do the authentication. I'm still trying to figure out exactly where the problem is. In the meantime, you can use temporary authentication, or re-install a previous version of httr, for example:

```
install.packages("http://cran.r-project.org/src/contrib/Archive/httr/httr_0.6.1.tar.gz", 
   repo=NULL, type="source")
library(httr)
library(Rfacebook)
token <- fbOAuth(app_id=..., app_secret=...)
```

**Comment by torrentpien** [comment]
I can't downgrade httr. Hope you can fix the problem of Rfacebook. tks.

**Comment by nicvel** [comment]
If you employ an access token from your app, the 2 hour limitation is lifted.
That is, go to https://developers.facebook.com/tools/explorer/, and in the “Application” drop down menu, change the default selection from the Graph API Explorer to one of your apps. Then, in the Get Token drop down menu, select “Get App Token”.

This App Token has as similar structure to the APPID/APPPSWD you have to provide to retrieve JSONS over https.

Hope it helps!

**Comment by caiomsouza** [comment]
It worked for me with the code below.

install.packages("http://cran.r-project.org/src/contrib/Archive/httr/httr_0.6.1.tar.gz", 
   repo=NULL, type="source")
library(httr)

**Comment by soyuznii** [comment]
thenks Caio for your response
how ever my issue is that i am not able to searchFacebook("search term",
lang="en", n= 500)
as i am able to searchTwitter("searhc term",lang ="en", n=500) the reason
being that facebook api has been upgraded or changed and so far i have
searched the web for a solution
is there a newer api or an alternative method to search for facebook posts?

**Comment by rajeev0306** [comment]
Hi Pablo

I'm getting an issue when i try to get my token. I'm using it on R console. The  log is here :

fb_oauth <- fbOAuth(app_id="Myid", app_secret="myid",extended_permissions = TRUE)
Copy and paste into Site URL on Facebook App Settings: http://localhost:1410
When done, press any key to continue...
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error: Deprecated: supply token object to config directly

As you have mentioned earlier that there are some issue with httr version so I tried to install the earlier version with below command
It worked for me with the code below.

install.packages("http://cran.r-project.org/src/contrib/Archive/httr/httr_0.6.1.tar.gz",
repo=NULL, type="source")

but getting following error
Installing package into ‘D:/Users/rajeevkg/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'http://cran.r-project.org/src/contrib/Archive/httr/httr_0.6.1.tar.gz'
Content type 'application/x-gzip' length 247531 bytes (241 KB)
downloaded 241 KB

* installing *source* package 'httr' ...
** package 'httr' successfully unpacked and MD5 sums checked
** libs

*** arch - i386
Warning: running command 'make -f "C:/PROGRA~1/R/R-32~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-32~1.1/share/make/winshlib.mk" SHLIB="httr.dll" OBJECTS="writer.o"' had status 127
ERROR: compilation failed for package 'httr'
* removing 'D:/Users/rajeevkg/Documents/R/win-library/3.2/httr'
* restoring previous 'D:/Users/rajeevkg/Documents/R/win-library/3.2/httr'
Warning messages:
1: running command '"C:/PROGRA~1/R/R-32~1.1/bin/i386/R" CMD INSTALL -l "D:\Users\rajeevkg\Documents\R\win-library\3.2" "D:/Users/rajeevkg/AppData/Local/Temp/Rtmpkh9pId/downloaded_packages/httr_0.6.1.tar.gz"' had status 1 
2: In install.packages("http://cran.r-project.org/src/contrib/Archive/httr/httr_0.6.1.tar.gz",  :
  installation of package ‘D:/Users/rajeevkg/AppData/Local/Temp/Rtmpkh9pId/downloaded_packages/httr_0.6.1.tar.gz’ had non-zero exit status

**Comment by rajeev0306** [comment]
can someone

**Comment by rajeev0306** [comment]
reply pls

**Comment by digitaliteter** [comment]
I have the same problem with instaR

**Comment by pablobarbera** [comment]
Wow, this was hard to fix! But everything should be working again now.

**Comment by torrentpien** [comment]
I have installed the new version (0.52). I have a further question. The console shows that Authentication complete and Authentication successful (thanks for your great job!!!). But I check fb_oauth. <Token> is empty. Is it normal? Because I can't get my friends' list, I don't know if it is caused by he problem of token code.

Thanks

**Comment by dayushan** [comment]
I have the same issue.


library(httpuv)
#install.packages("http://cran.r-project.org/src/contrib/Archive/httr/httr_0.6.1.tar.gz",repo=NULL, type="source")
#install.packages("Rfacebook")
library(rjson)
library(Rfacebook)

library(httr)
Sys.setenv("HTTR_SERVER_PORT" = "1410/")


# 1. Find OAuth settings for facebook:
#    http://developers.facebook.com/docs/authentication/server-side/
oauth_endpoints("facebook")
# 2. Register an application at https://developers.facebook.com/apps/
#    Insert your values below - if secret is omitted, it will look it up in
#    the FACEBOOK_CONSUMER_SECRET environmental variable.
myapp <- oauth_app("facebook", "AppID", "Appsecret")
permissions<-"user_birthday,user_education_history,user_hometown,user_location,user_website,user_work_history,publish_actions,user_friends,email"
Sys.setenv("HTTR_SERVER_PORT" = "1410/")
# 3. Get OAuth credentials
facebook_token <- oauth2.0_token(
  oauth_endpoints("facebook"),
  myapp,
  scope=permissions,
  type = "application/x-www-form-urlencoded"
)

Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached

fb_sig<-sign_oauth2.0(fb_token)
Deprecated: supply token object to config directly
