### ISSUE TITLE
Can Rfacebook extract data from reviews Section in Facebook Pages

### ISSUE THREAD

**Issue by upchair** [pablobarbera/Rfacebook#40]
Pablo Hi,

Please I have been trying to extract posts/comments  in the reviews section of public facebook pages to no avail.

Please which of the commands in the Rfacebook package can extract data successfully from the reviews section

Thank You 

Richard

**Comment by pablobarbera** [comment]
Hi @upchair, unfortunately it doesn't seem reviews are available through the public Graph API (or at least I cannot find them) https://developers.facebook.com/docs/graph-api/reference/page/
