### ISSUE TITLE
Error: is.request(y) is not TRUE

### ISSUE THREAD

**Issue by tokumotion** [pablobarbera/Rfacebook#41]
Hi Pablo,

I'm getting this message from the getPage() function:

     Error: is.request(y) is not TRUE

I googled the error and it seems it is a `httr` issue, as they have recently updated the package to 1.0.0 version.

**Comment by pablobarbera** [comment]
Hi @tokumotion, I'm not able to replicate the error, but perhaps the update I just made to Rfacebook to make it work with httr 1.0.0 fixed it too? If not, please let me know and I'll reopen the issue and look more into it. Thanks!

**Comment by tokumotion** [comment]
Hi Pablo, I tried to use the package with *httr* v. 1.0.0 but kept getting the same message.

I tried to download the new version, but got this message:

    devtools::install_github("pablobarbera/Rfacebook")
    Downloading github repo pablobarbera/Rfacebook@master
    Error: Does not appear to be an R package (no DESCRIPTION)

**Comment by tokumotion** [comment]
Hi Pablo,
I think I might found the reason. Now FB is asking developers to submits their apps before granting data permission (read_pages, read_insights and read_groups). Therefore my token is not valid until I have gotten those permissions.

Could it be it? Or is anyone around to replicate the error?

**Comment by pablobarbera** [comment]
@tokumotion I was still not able to replicate the exact same error you were getting, but you're right that with new Apps the default options required App Review, so I fixed that. Thanks!

**Comment by tokumotion** [comment]
@pablobarbera should I create a new app since my old app isn't approved?

**Comment by thetoubi** [comment]
@tokumotion I've got the same problem here. Did you find out how to get it running again?

**Comment by tokumotion** [comment]
I couldn't. The problem is that your fb app is not authenticated by FB and now, in order to get the insights data, you need to have your app authenticated.
If you want to get public data, use the temporal token from the Graph Explorer. Otherwise, you have to send your app to review.

**Comment by thetoubi** [comment]
@tokumotion Okay, thank you for the quick response! I didn't know about the temporal token, so thanks for the hint.
