### ISSUE TITLE
Crawl contents from groups

### ISSUE THREAD

**Issue by cho7tom** [pablobarbera/Rfacebook#42]
Hello,
First of all congratulations for this great package.
I am wondering how to crawl contents from 'group' pages, such as for example: www.facebook.com/groups/Epilepsyawareness/
Is that feasible? Would it be feasible to develop a 'getGroup' function similar to getPage to complete this task?
Thank you very much in advance for your views on this!
Best regards

**Comment by pablobarbera** [comment]
Thanks for the suggestion! This has been in my to-do list for a while, and it turned out to be easier than I thought to implement.

**Comment by cho7tom** [comment]
Dear Pablo,
I just tested getGroup: it works perfect for me!
Many thanks for this,
Regards
