### ISSUE TITLE
Can´t retrieve large periods for  "page_impressions_by_country_unique"

### ISSUE THREAD

**Issue by mcpasin** [pablobarbera/Rfacebook#43]
Hi Pablo,

I´d like to retrieve data for the "page_impressions_by_country_unique" metric over a large period of time, let say 6 months.

When I run the query with a period of 2 months, it seems to work fine. E.g:
data<-getInsights(object_id="xxx", token, metric="page_impressions_by_country_unique", period = "day",parms="&since=2015-01-01&until=2015-02-28")

However if the period gets larger, e.g.:
data<-getInsights(object_id="xxx", token, metric="page_impressions_by_country_unique", period = "day",parms="&since=2015-01-01&until=2015-03-31")

I get the following error:
Error in data.frame(unlist(x$data[[1]]$values[[i]]$value), end_time = x$data[[1]]$values[[i]]$end_time,  : arguments imply differing number of rows: 0, 1

Or in other cases, I get an error saying "Invalid Token".

I am using a temporary token. Do you have any idea why I can´t get the data?

Thank you very much,
Marco

**Comment by KeonCummings** [comment]
Facebook only allows you to select 180 days at a time.

**Comment by andrewgeisler** [comment]
@KeonCummings Is correct. When I've had to pull for longer time periods, I've either used a loop to cycle through calling different date ranges or if it's just a couple, I might just do it twice.

What are the situations where you're getting an Invalid token response?
