### ISSUE TITLE
Authenticating from RStudio Server

### ISSUE THREAD

**Issue by tokumotion** [pablobarbera/Rfacebook#49]
I'm trying to authenticate a Facebook session from RStudio Server but when I try to connect to authenticate in browser (http://localhost:1410/), I cannot connect as connection is refused.

Anyone else got this problem? Tried using the local machine token file but got the same problem.

**Comment by windrago** [comment]
Yes, it's a permission issue on the FB applicaiton side. I don't have access to my settings right now but it's pretty straightforward to change.

On the R side try this, if this fails then you settings (permission wise) on the FB end are not correct
me <- getUsers("me", token=fb_oauth)
my_friends <- getFriends(token=fb_oauth, simplify=TRUE)
my_friends_info <- getUsers(my_friends$id, token=fb_oauth, private_info=TRUE)

**Comment by tokumotion** [comment]
Hi @Windrago, when you have the time please share your settings with us.
Don't know how to change the app conf on Facebook side to solve this trouble.
When I use the token on local machine, it works but I cannot authenticate on RStudio Server.
Thanks!

**Comment by tokumotion** [comment]
Hi @Windrago, when you have the time please share your settings with us.
Don't know how to change the app conf on Facebook side to solve this trouble.
When I use the token on local machine, it works but I cannot authenticate on RStudio Server.
Thanks!

**Comment by windrago** [comment]
I realized only now that your issue is wtith RStudio Server. Sorry, if it does work on your RStudio Client which was my issue then I can only conclude that there's a rerouting that is causing the OAuth to fail.

**Comment by Satadam** [comment]
I'm having the same issue @tokumotion!

Not sure if this is helpful but I got it working sort of on my shiny-server ec2 by authenticating on my desktop local machine using the http://localhost:1410 redirect. Then saved the token and transferred to my project on the server.

Think this is only valid for 2 months so looking for a solution to get the Rfacebook package working on shiny-server. If not I'll have to use httr myself :(

**Comment by tokumotion** [comment]
Hi @Satadam, I did that but didn't work. It asked me to reauthenticate the token and got stuck into the same problem.
