### ISSUE TITLE
getUsers in Rfacebook throwing an error

### ISSUE THREAD

**Issue by rohit4084** [pablobarbera/Rfacebook#5]
Hi,

getUsers in Rfacebook is throwing following error.

Command Used:  me <- getUsers("me", token=fb_oauth)
Error message: Error in callAPI(query, token) : 
  (#12) username is deprecated for versions v2.0 and higher

Has facebook disabled call back by this API. Is there any alternate way.

Thanks

**Comment by johnnoelvictorino** [comment]
forked this [repo] (https://github.com/pablobarbera/Rfacebook/pull/12)
then in R
if you have not installed devtools
`install.packages("devtools")`
`require("devtools")`
`install_github("your-username/Rfacebook", subdir = "Rfacebook")`
`require(Rfacebook)`

It worked for me

**Comment by pablobarbera** [comment]
Hey, thanks for the suggestion! I now see where the problem was. I fixed the getNetwork function so that it now works with both 1.0 and 2.0 API tokens.

**Comment by holborn25** [comment]
Could you make a short summary please. I try to do all what you propose, but i don't succeed in writing the good code. What do u call "username" ? the git_hub nIckname ? 
Thanks a lot !!!

Regards.

**Comment by Chikooo** [comment]
I also faced the same issue. I am using temporary token and not the other one.
Solution is just update the packages related to Rfacebook. I updated "Rfacebook" and "devtools" and issue got resolved. Thanks

**Comment by Gaurishankar11** [comment]
could not find function "callAPI"

**Comment by Gaurishankar11** [comment]
I am gettng this error

**Comment by Sherezaderivas** [comment]
Hola Pablo! Help me. How do i access to other information?
 
> publico <- getUsers("Estampas",token=appminfb)
Error in callAPI(query, token) : 
  (#100) Tried accessing nonexisting field (first_name) on node type (Page)

**Comment by CarlosDutra** [comment]
I am getting the same error.

**Comment by marperry** [comment]
is there an ETA on the fix.  is a fix possible?
