### ISSUE TITLE
getInsights not getting Page Video Posts metrics 

### ISSUE THREAD

**Issue by andrewgeisler** [pablobarbera/Rfacebook#53]
As referenced in issue #52,

> I've been playing with the function last night and found that getInsights work with mostly all the metrics stated here. 
From Page Video Posts downwards I couldn't get any data. 

Referenced link: https://developers.facebook.com/docs/graph-api/reference/v2.1/insights

**Comment by andrewgeisler** [comment]
@tokumotion 

I am able to retrieve page video metrics for a page with videos that I have access too. One thing I was reminded of is that the object_id needed for this metric is the id of a _**post**_ not a _**page**_. If I attempt to call a video metric for a page object, I do get the following error:

> Error in getInsights(object_id = kcId, token = token, metric = "domain_stories",  : 
  No data available. Are you the owner of this page? See ?getInsights.

Is that the error you were receiving?
Can you confirm if you're requesting the metric for a post not a page?

**Comment by tokumotion** [comment]
Great, thanks

**Comment by tokumotion** [comment]
Hi @andrewgeisler got any news on this issue? Is the problem on my end?

**Comment by chennav** [comment]
@andrewgeisler @tokumotion,
Where you able to retrieve data for "domain_feed_clicks" metric or any other metric?
Here's how I invoke the API,
`https://graph.facebook.com/v2.5/espn/insights/domain_feed_clicks?access_token=_APP_ID_|_APP_SECRET_`

Thanks.

**Comment by dkomd** [comment]
Hi, 
The above  version does not work. Is there a way to get the reactions, likes, comments, for video_insights given that the getInsights has depreciated.

**Comment by tokumotion** [comment]
@dkomd hi!

There is a function for that: `getPage(x = yourpage, token = yourtoken ,reactions = TRUE)`

**Comment by dkomd** [comment]
@tokumotion No, getPost doesn't have such attributes like getting reactions or time of day.

**Comment by tokumotion** [comment]
@dkomd there is a function `getReactions()` in the package:

```
getReactions {Rfacebook}	R Documentation
Extract total count of reactions to one or more Facebook posts

Description

getReactions retrieves information from a single or multiple posts, returning the total count of reactions of each type (like, love, haha, wow, sad, angry).

Usage

getReactions(post, token, verbose = TRUE)
Arguments

post	
A post ID, or a vector of post IDs
token	
Either a temporary access token created at https://developers.facebook.com/tools/explorer or the OAuth token created with fbOAuth.
verbose	
logical, default is TRUE, which will print additional information on the console.
```

**Comment by abrohi** [comment]
@pablobarbera @tokumotion @andrewgeisler 

Hi!

Its my first post, so apologies if I am not going by protocol. 

Have you managed to resolve the issue in using 'getinsights' post level? I am getting the same error as tokumotion. See below code and error.

postinsights <- getInsights(
  token = token,
  object_id = "7532951562_10155171604576563",
  metric = "post_impressions")

**Comment by abrohi** [comment]
@pablobarbera  @tokumotion @andrewgeisler

Hi!

Its my first post, so apologies if I am not going by protocol.

Have you managed to resolve the issue in using 'getinsights' post level? I am getting the same error as tokumotion. See below code and error.

```
postinsights <- getInsights(
token = token,
object_id = "7532951562_10155171604576563",
metric = "post_impressions")
```

`_Error: No data available. Are you the owner of this page? See ?getInsights._`

Note, I am using a temporal token

Many thanks in advance, 

Amir
