### ISSUE TITLE
GetInsights() Post Interests Insights error

### ISSUE THREAD

**Issue by Andrewm4894pmc** [pablobarbera/Rfacebook#58]
Hi, 

When i  make a call such as:

`getInsights(object_id="XXX", fb_access_token, metric = "post_interests_impressions_unique")`

I get the below error:

_Error in names(tmp) <- c("value", "variable") : 
  'names' attribute [2] must be the same length as the vector [1]_

Looks like maybe the api response structure might be causing issues for the function.

Seems to only happen for insights in the "post_interests_..." family.

**Comment by Andrewm4894pmc** [comment]
sorry i should add this is when passing a post_id

**Comment by andrewgeisler** [comment]
@Andrewm4894pmc Thanks for clarifying. I assumed since the metric is for a post. It looks like that metric should return numbers related to impressions targeted to an audience. I'm currently trying to find a post that I have access too that was targeted in such a way so I can recreate the issue. If I use any random post_id, I do get that same error because there the values returned is an empty set. That doesn't help me understand what it "should" do when there is data. Are you able to use the api explorer to verify that there is data there for that metric and post_id?

I'll keep you posted as I continue to look into it.

**Comment by Andrewm4894pmc** [comment]
Ahh i see it's related to audience targeting - i don't think we do any of
that so not sure i'd have an example with data.

Empty response seems to look like:

{
      "name": "post_interests_impressions_unique",
      "period": "lifetime",
      "values": [
        {
          "value": {
          }
        }
      ],
      "title": "Lifetime Total Matched Audience Targeting Reach",
      "description": "Lifetime: The total number of people matched the
audience targeting on Page post on News Feed was served. (Total Count)",
      "id":
"12616252196_10153388571927197/insights/post_interests_impressions_unique/lifetime"
    }

On Tue, Feb 23, 2016 at 7:27 PM, Andrew Geisler <notifications@github.com>
wrote:

> @Andrewm4894pmc <https://github.com/Andrewm4894pmc> Thanks for
> clarifying. I assumed since the metric is for a post. It looks like that
> metric should return numbers related to impressions targeted to an
> audience. I'm currently trying to find a post that I have access too that
> was targeted in such a way so I can recreate the issue. If I use any random
> post_id, I do get that same error because there the values returned is an
> empty set. That doesn't help me understand what it "should" do when there
> is data. Are you able to use the api explorer to verify that there is data
> there for that metric and post_id?
>
> I'll keep you posted as I continue to look into it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pablobarbera/Rfacebook/issues/58#issuecomment-187853150>
> .
>



-- 
Andrew Maguire | Data Scientist
11175 Santa Monica Boulevard, Los Angeles, CA 90025
Office: +1.310.321.5000 · Email: andrew.maguire@pmc.com
[image: PMC]

**Comment by andrewgeisler** [comment]
Possibly related to issue #76 regarding parsing empty results returned by FB.
