### ISSUE TITLE
Support for FB reactions

### ISSUE THREAD

**Issue by pablobarbera** [pablobarbera/Rfacebook#61]
This doesn't seem to be available with the current version of the API, but I'll implement it if that changes.

**Comment by workah0lic** [comment]
I think facebook enabled fetching all reactions with v2.6 of their graph-api (I just tried it on graph api explorer). Looking forward to see this functionality in Rfacebook - big thanks for your work and constant improvements :)

**Comment by diegocgaona** [comment]
hi @workah0lic ,
To get the reactions by day using a page id, you can use something like this:

```
fb_page_reactions <- getInsights(object_id = fbpage_id, token = fb_oauth, metric = c('page_actions_post_reactions_total'), 
                                   period = c('day'), parms = paste0("&since=", twomonth_s, 
                                                                     "&until=", as.character(currentdate)))
```
It works without problem to me.

But if you want to get the reactions by post (I want it), I think they need to update the getPost function from Rfacebook. The Facebook API have a new "reactions" endpoint for "post" (https://developers.facebook.com/docs/graph-api/reference/v2.6/post).
