### ISSUE TITLE
Reduce the amount of data you're asking for?

### ISSUE THREAD

**Issue by jrosen48** [pablobarbera/Rfacebook#62]
Thanks for such a great tool. When I ran the following code:

```
> page <- getPage("humansofnewyork", token, n = 5000)
```
The following message is output, although in the vignette there does not appear to be a limit on the number of posts which can be requested:

```
100 posts 
Error in callAPI(url = url, token = token) : 
Please reduce the amount of data you're asking for, then retry your request
```

Are there any strategies to request a large number of posts without encountering this message?

**Comment by Eflores89** [comment]
The same happens to me with: 
`nytimes <- getPage("nytimes", token=fb_oauth, n = 200)`

Is it maybe something with Facebook's API?

**Comment by pablobarbera** [comment]
Ugh, I'm getting the same error. Yes, it seems something changed in the API. I'll try to fix it in the next couple of days.

**Comment by pablobarbera** [comment]
Reducing the number of posts to be queried with each API call seems to fix the issue. Thanks for reporting it!

**Comment by raulmilan** [comment]
Indeed thank you so much. I love working with your package. However, right now, no matter how much I am reducing getPage (down to 50) I am always getting "Error in callAPI(url = url, token = token) : 
  Please reduce the amount of data you're asking for, then retry your request" Is there anything to do? I updated my package to 0.6.3, tried smaller time windows, etc. Any help would be most highly appreciated...

**Comment by thetoubi** [comment]
I ran into the same problem (Rfacebook 0.6.3). After checking my code with other fan pages I noticed that only a few pages produced this error (in my data set nine out of about 250). After reducing the number of posts, it worked with limits between 39 (worked for one page),  79 (worked for multiple pages), and 1100 (worked for one page). Therefore I wonder, if it is a privacy setting issue (but I'm not sure if there is such an option for page administrators) or if it is an API issue. Btw. love the package, thanks a lot Pablo!

**Comment by pablobarbera** [comment]
Yes, I think for some pages with a lot of comments, there's a limit on how many posts can be queried at a time. I reduced this to 25 posts per API call, which may slow things down a bit, but hopefully should fix the problem for everyone.

**Comment by Eflores89** [comment]
Looking forward to trying it out. Congrats on the package. :+1:

**Comment by dengelha** [comment]
IT WORKS GREAT !!!
RRockstar and genius <- @pablobarbera ;-)
Thank you so much !!!

**Comment by dengelha** [comment]
Uuuuh, I tried it on a different computer with the newest R-release, both the dev-version from Git and the regular CRAN-version and it threw the following error.
> Error in loadNamespace(name) : es gibt kein Paket namens ‘curl’

Translation: there is no package called 'curl'

Any idea?
Thx for the great work!

**Comment by bobokdalibor** [comment]
It seems that Facebook again reduced the amount of data you can download. Now the maximum I can get is 80 posts, after that I receive an error _"Error in callAPI(url = url, token = token) : 
  Please reduce the amount of data you're asking for, then retry your request"_ Is there any way how to workaround this? I am doing my Thesis using Rfacebook and this is pretty annoying. 

PS: Amazing package Pablo,

**Comment by pablobarbera** [comment]
@bobokdalibor Can you try with the latest version of Rfacebook from GitHub? I reduced the number of posts that are being queried in each API call to 25, so hopefully that should take care of this. If not, another option would be to query for specific periods inside a loop (e.g. in periods of 10 days), and then putting everything together. I hope this helps!

**Comment by coolankit** [comment]
Hello Everyone,

Has anyone faced issue regarding quantity of the data set received by this calling getPage() method ?
Currently, I'm calling this function on loop to fetching data for multiple dates and receiving less amount of posts as compared to a tool which is uses PHP API for same task and the difference is huge like ~600 posts difference in the course of 3 months data.
my API calling piece of code is

```
tryCatch(fb_page<-getPage(page=page_name,n=100,token=AT,since = as.Date(df_fbpage$Start[j]),until =as.Date(df_fbpage$End[j]))
,error=function(e){})

```
    
Could anyone explain it what I'm doing wrong ?

Thanks in advance
