### ISSUE TITLE
Post images to FB

### ISSUE THREAD

**Issue by debsush** [pablobarbera/Rfacebook#63]
Hi,

Very excited to see this new package.  I have a shiny app which creates plots.  I would like to publish those charts onto Facebook.  Is it possible through your package.  If not, can you suggest a way.  I think the Graph API in Facebook allows such functionality.

Thank you,
SD

**Comment by pablobarbera** [comment]
Not possible at the moment, but a way around it would be to upload the picture to imgur.com with R (see [package here](https://cran.r-project.org/web/packages/imguR/index.html)), and then post the link to Facebook using updateStatus() adding the URL into the link argument.
