### ISSUE TITLE
getInsights on post_id returns null object

### ISSUE THREAD

**Issue by diegocgaona** [pablobarbera/Rfacebook#64]
Hi,

First, thanks for this good and useful package!!!

I'm trying to get info about post_consumptions_by_type, but when I try, I get back a NULL object only, no error, no list, only test as a NULL object.

```
test <- getInsights(object_id='1522614931338640_1678950812371717',
                        token=fbtoken, metric='post_consumptions_by_type', period='lifetime')
```
I tried some other post metrics as:
post_storytellers
post_stories
post_impressions

The result is the same.

In the Graph Explorer,  I did:

`GET /2.5/1522614931338640_1678950812371717/insights/post_consumptions_by_type`

And I receive:

```
{
  "data": [
    {
      "name": "post_consumptions_by_type",
      "period": "lifetime",
      "values": [
        {
          "value": {
            "other clicks": 43,
            "link clicks": 46
          }
        }
      ],
      "title": "Lifetime Post Consumptions by type",
      "description": "Lifetime: The number of clicks anywhere in your post, by type. (Total Count)",
      "id": "1522614931338640_1678950812371717/insights/post_consumptions_by_type/lifetime"
    }
  ],
```

I tried using the temporary token (the same used in the Graph Explorer) and the fb_oauth with the same results. 

I'm using the wrong syntax? Work for others?

Thanks!

**Comment by andrewgeisler** [comment]
@diegocgaona Sorry for the delay. I'll take a look and keep you posted.

**Comment by andrewgeisler** [comment]
@diegocgaona 

I've pushed a fixed to my fork of this repo. Can you reinstall from there and give it a test before I open a pull request? I was able to recreate the problem and was then able to pull these metrics after the fix. 

```
require(devtools)
install_github("andrewgeisler/Rfacebook", ref='issue64', subdir="Rfacebook")
```

**Comment by diegocgaona** [comment]
Worked fine in my test too!!    :+1: 

Thanks @andrewgeisler !! Great job!
