### ISSUE TITLE
Error in token$sign : object of type ‘S4′ is not subsettable

### ISSUE THREAD

**Issue by aronn80** [pablobarbera/Rfacebook#66]
After running fbOAuth i got something like that:

In class(fb_oauth)[4] <- "v2" :

Defined class(x) for multiple strings ("Token2.0", "NA", ...); result will no longer be an object S4.
 
Can you explain to me what's going on?  I've read a lot and tried all possible solutions but none of then worked for me.

Best,

Armando Neto

**Comment by pablobarbera** [comment]
Can you check if authentication via a temporary token works? What's your sessionInfo() ?

**Comment by aronn80** [comment]
I think that I'm already using a temporary token.

How can I check the session info?
