### ISSUE TITLE
Effort to use callAPI for pulling comments on comments throws an Error

### ISSUE THREAD

**Issue by ypanagis** [pablobarbera/Rfacebook#70]
Hi and thank you for the wonderful module. I am trying to implement a function to bring all comments subsequent to a comment . According to GraphAPI the syntax for this is:
`<comment_id>/comments`. When I try however to use `callAPI` for that purpose, it throws the following error
```
 Error in callAPI(url = url, token = token) : 
  Unknown path components: /comments&access_token=
```
By looking at `callAPI` I see that it concatenates `access_token` by using `&`, i.e. 
```
	if (class(token)[1]=="character"){
		url <- paste0(url, "&access_token=", token)
		url <- gsub(" ", "%20", url)
		url.data <- GET(url)
	}

```

It seems that GraphAPI expects to see it concatenated with a question mark. Would you suggest a way to circumvent this, apart from the obvious "hack" to change `&` to `?`?

**Comment by pablobarbera** [comment]
Thanks! The following works for me:

```r
comment_id <- '10153800509846749_10153800516131749'
url <- paste0('https://graph.facebook.com/v2.6/', comment_id, '?fields=comments')
r <- callAPI(url, token)

```
You will need to experiment with `limit` and pagination in order to get all of them, but this should work :-)

**Comment by ypanagis** [comment]
Sweet! Thanks for the reply. I will use it asap
