### ISSUE TITLE
getLikes() returns

### ISSUE THREAD

**Issue by jrosen48** [pablobarbera/Rfacebook#73]
When I use getLikes(), it returns:

`User not found, or token is not authorized.`

I tried the answer suggested in [this SO question](http://stackoverflow.com/questions/33820540/user-not-found-or-token-is-not-authorized-in-r), but saw the same message returned. 

Here is all the code I used:

```
fb_oauth <- fbOAuth("XXX", "XXX", extended_permissions = TRUE)
save(fb_oauth, file="fb_oauth")
load("fb_oauth")
getLikes("XXX", token = fb_oauth) 

```

Is anyone else experiencing this issue?

**Comment by pablobarbera** [comment]
Unfortunately it seems you can now only get likes for the authenticated user ("me") through the API, so the only use for this function is the example in the documentation.
