### ISSUE TITLE
Problem in trying to authenticate

### ISSUE THREAD

**Issue by debsush** [pablobarbera/Rfacebook#74]
When I tried to authenticate from my desktop RStudio, I get the following

Copy and paste into Site URL on Facebook App Settings: http://localhost:1410/ 
When done, press any key to continue...
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Authentication successful.
<Token>
<oauth_endpoint>
 authorize: https://www.facebook.com/dialog/oauth
 access:    https://graph.facebook.com/oauth/access_token
<oauth_app> facebook
  key:    578060949022560
  secret: <hidden>
<credentials> access_token, expires
--- 

Now if I try the below
save(fb_oauth, file="fb_oauth")
I get
Error in save(fb_oauth, file = "fb_oauth") : object ‘fb_oauth’ not found

What am I doing wrong here?

**Comment by tokumotion** [comment]
Hey @debsush, you might want to try this way to authenticate a FB app for R to use: 

https://www.reddit.com/r/rstats/comments/426059/problem_with_function_oauth20_in_package_httr/cz8l6i7

**Comment by debsush** [comment]
Thank you for the response.  Much appreciate it.
I tried your method.  The facebook auth page opened when I tried the below

library(httr)
app <- oauth_app('facebook', appid, appsecret)
Sys.setenv("HTTR_SERVER_PORT" = "1410/")
tkn <- oauth2.0_token(
oauth_endpoints('facebook'), app, scope = 'ads_management',
type  = 'application/x-www-form-urlencoded', cache = FALSE)

Now when I clicked on "Okay" in the FB page, it shows 

This site can’t be reached

localhost refused to connect.

Was wondering if I am doing anything erroneous while created the App ID and App Secret.  Long story short, the authentication fails and I do not get the token back from Facebook. 

Do I need to complete the App Review form in  https://developers.facebook.com/apps/ to get it working?

Would really appreciate if you could come over a Skype session and  I can show my webapp and screen to you.  I have been trying this for quite sometime now but to no avail :(

I may be doing something really stupid as I am new to this world.  Any help from here on from you will be much much appreciated

Thank you
SD

**Comment by tokumotion** [comment]
Hi @debsush, no. You don't need to get the App Review for the library to work.

Did you follow the process to create the app as written in the reddit comment?
You need to assign your App ID to the variable `appid` and your App Secret to the `addsecret` variable.

That might be it.

**Comment by debsush** [comment]
Understood the issue.  When run locally it works fine but I was having my RStudio installed over AWS EC2.  Thank you very much for the help.  Now if I want to run the script from my app https://dmarket.shinyapps.io/Main  do I now need to change the line Sys.setenv("HTTR_SERVER_PORT" = "1410/") and the settings in my APPID?

**Comment by tokumotion** [comment]
@debsush I cannot help you with that. I ran into the same problem a while ago and haven't found a solution for authenticating an app from RStudio Server. Sorry

**Comment by debsush** [comment]
Please keep me posted in case you are able to crack the puzzle.

**Comment by debsush** [comment]
I got a negative answer back from shinyapps:

https://groups.google.com/forum/#!topic/shinyapps-users/THbYd_Z24Fg

My question is what kindof token is generated by your code?  Is it a user token or an app token or a client token.  Long story short, if I store the token generated locally and use it as an argument in my webapp, will it allow different users to share the content of my app to their own timeline.
If no, can I create a facebook page and make sure that all sharing from my webapp is posted onto that webpage?

**Comment by debsush** [comment]
In the local environment, I used the below per your suggestion and this works fine

      library(httr)
    app <- oauth_app('facebook', appID, appsecret)
    Sys.setenv("HTTR_SERVER_PORT" = "1410/")
    fb_oauth <- oauth2.0_token(
      oauth_endpoints('facebook'), app, scope = 'ads_management',
      type  = 'application/x-www-form-urlencoded', cache = FALSE)
    save(fb_oauth, file="fb_oauth")
    load("fb_oauth")
    tkn <- fb_oauth$credentials$access_token
    fbname <- getUsers("me", token=tkn)
    updateStatus("Hello World", token=tkn, link = "www.shinyapps.io")

Now in shinyapps.io I used the following:
      load("fb_oauth")
      tkn <- fb_oauth$credentials$access_token
      fbname <- getUsers("me", token=tkn)
      updateStatus(paste("Analysis by ",fbname$name," using www.gocharting.com",sep=""), token=tkn, link = capture)

2 observations when above is executed in shinyapps.io:
1.  It posts the link in my facebook timeline even when someone else is logged into facebook in the browser.
2. It only posts once when post button in ui.R is clicked.  Subsequent clicks do not post anything onto FB

Please let me know what I may be doing wrong here

SD

**Comment by debsush** [comment]
I even raised this issue with Hadley (httr github) but even he is of the opinion that there is no solution to it now.  This is so frustrating.  It seems impossible to create a professional enterprise webapp in shinyapps.io

**Comment by tokumotion** [comment]
Hi @debsush,

Maybe @pablobarbera can help you with this issue.

I raised this a while back in Issue #49

**Comment by debsush** [comment]
I have a query owning to my lack of knowledge in this field.  I used the googleAuthR package and it allows us to setup the URL in the Google Console page like in case of Facebook.  Now in Facebook, we are providing the port 1410 while in Google, we can specify any port we want and then run the shinyapp on that port. shiny::runApp('App',port=1221) locally.  Also in Google console, we can specify the webapp URL (e.g., https;//dmarket.shinyapps.io/Main/) if we are running our app on shinyapps.io.  This allows user authentication every time a user login in or wants to perform some activity using Google API.  Now my question is why can't we do the same with RFacebook?  Is the port 1410 mandated by FB?  Or is it a limitation of RFacebook?

**Comment by pablobarbera** [comment]
Hi @debsush -- sorry for the slow reply to this. The port is mandated by the way httr creates and authenticates the token, so unfortunately nothing I can do here to fix this since Rfacebook relies on httr to do the authentication. I saw that you opened an issue on the httr repository as well. If you found any solution, please share it here :) I'll close this for now.

**Comment by debsush** [comment]
Hi Pablo,

I will definitely share the results if I happen to find it.

On a separate note, I was wondering if you have seen the googleAuthR
package by Mark Edmondson.  His package allows using google APIs even in a
shiny application along with an ability to login using google credentials.
I understand that you cannot use that in RFacebook for shiny applications
hosted over shinyapps.io because of the port issue but you can definitely
use it on shiny applications hosted on DigitalOcean etc.   He has used a
unique method of creating an interactive envirnment within the shinyapp to
store the token which allows the user to use the token and call the APIs
within the shinyapp session.  It would be super helpful if you could also
incorporate his method in your package and provide a shinyapp demo for your
users.


The normal httr method will not work as it does not create an interactive
environment within shinyapp.  See the ticket I had raised on httr github
below and the response was not useful at all

https://github.com/hadley/httr/issues/377


googleAuthR references:
1. https://github.com/MarkEdmondson1234/googleAuthR
2. https://github.com/MarkEdmondson1234/googleID

I will be more than happy to contribute to this project enhancement.
Please let me know

Regards,
SD

**Comment by pablobarbera** [comment]
@debsush This sounds like a great idea to me! I know for teaching purposes many people would find it useful too. Unfortunately, I don't have time at the moment (or the expertise!) to implement it, but if you want to work on this, your contribution would be very welcome. 

My policy re: these situation is that if you do any major contribution to the package (and this one would be), I will add you as author in the DESCRIPTION file. 

I don't want to do any major changes on the fbOAuth function, but this could be a different function, or something that is not the default behavior of fbOAuth, mostly to ensure that all past code still works. Feel free to get in touch with me via email if it's easier than here. Thanks for suggesting this!!
