### ISSUE TITLE
Get longer time series from getInsights()

### ISSUE THREAD

**Issue by tokumotion** [pablobarbera/Rfacebook#75]
Hi, 

Currently FB API only allows you to pull data from a period of 90-ish data points (days, weeks, months, years) max. Can the `getInsights()` function handle multiple requests in case the required time frame is longer than 90-ish data points?

Or at least make the error message clearer about this?

Thank you!

**Comment by andrewgeisler** [comment]
Currently, the parms argument in getInsights() is just a string. It would probably entail fairly significant changes to build in functionality to intelligently parse though supplied dates and build request for acceptable date ranges. 

@pablobarbera The error message returned in versions 2.4+ is pretty descriptive. I'm not sure how callAPI handles error messages returned by FB.

**Comment by pablobarbera** [comment]
Thanks @andrewgeisler for chiming in on this! In theory callAPI should return the same error message as the API, so hopefully that's informative enough. I'm also hesitant to expand this function for the reasons you suggest, and as I've mentioned earlier I don't admin any page at the moment, so it would be hard for me to work on that! :-/ I'll close this for now.
