### ISSUE TITLE
getGroup vs getPage

### ISSUE THREAD

**Issue by AutismSocialMediaAnalysis** [pablobarbera/Rfacebook#80]
As expected, the getPage function returns posts from the page listed in the function. For example, getPage(75219157496, fb_oauth, n=20) returns the 20 most recent posts from Autism Speaks.

getGroup(75219157496, fb_oauth) returns posts from Autism Speaks (from_id=75219157496) as well as other IDs.  Could you clarify where these other IDs are coming from?  I looked at the Autism Speaks Facebook page, but didn't see the other posts there.

thank you.

**Comment by pablobarbera** [comment]
These other IDs correspond to posts on the group by people other than the admin of the page (see https://www.facebook.com/autismspeaks/posts_to_page/). I have added an option to getGroup() to return only posts by the admin of the page:

gr <- getGroup(75219157496, fb_oauth, feed=FALSE) # only posts by admin
gr <- getGroup(75219157496, fb_oauth, feed=TRUE) # all posts on group (default)

Thanks for reporting this!
