### ISSUE TITLE
Error "unexpected character '<'"

### ISSUE THREAD

**Issue by VenkatArchitect** [pablobarbera/Rfacebook#85]
I'm getting an error for getPage with the latest RFacebook.

fb_since_date<-"Sat Aug 27 03:33:38 2016"
fb_until_date<-"Sat Aug 27 04:33:38 2016"
fb_oauth <- get_fb_auth()

content<-getPage("fantasyworld", fb_oauth, n = 2000, since=fb_since_date,until=fb_until_date, feed = TRUE, reactions=TRUE)

Error in rjson::fromJSON(rawToChar(url.data$content)) : 
unexpected character '<'

Note: I tried with different date/time formats, but I get the same error.  It seems like the getPage
does not like space character in the since and until dates.

**Comment by adhiman356** [comment]
Hi, I am also getting the same error. 

Error in rjson::fromJSON(rawToChar(url.data$content)) : 
unexpected character '<'

It would be good if you can help in case you have solved the error

**Comment by adiguzelomer** [comment]
any news on this issue ?

**Comment by pablobarbera** [comment]
This was probably the same issue as in #88 . The most recent version of Rfacebook (now on GitHub) should have fixed it. Thanks!

**Comment by RuaIsmail** [comment]
i am getting the same error 
 Error in fromJSON(rawToChar(url.data$content)) : unexpected character '<'

**Comment by l4u532** [comment]
same here

**Comment by aseyedia** [comment]
I am also getting it
