### ISSUE TITLE
Cannot crawl closed facebook groups

### ISSUE THREAD

**Issue by adhiman356** [pablobarbera/Rfacebook#86]
Hi everyone,

I cannot crawl closed FB groups even if I am a part of it. The result is always zero(0) posts.

I would be thankful if anyone could help me with this.

**Comment by pablobarbera** [comment]
Hi @adhiman356 , unfortunately you can only crawl public FB groups (https://developers.facebook.com/docs/graph-api/reference/v2.8/group/feed) and private groups if you are the admin of that group.
