### ISSUE TITLE
Language bug when crawling vietnamese fanpage

### ISSUE THREAD

**Issue by hvhungoc** [pablobarbera/Rfacebook#87]
I've tried to crawl this vietnamese fanpage with code like:
beat <- getPage(page="331230823580420", token=my_oauth,n=20) 
And the result comes out with language bug in the column message, how can i fix it?

I tried the setlocale code: Sys.setlocale(category = "LC_ALL", locale="Vietnamese_Vietnam.1258")
But it not fix at all 
Help me please

**Comment by pablobarbera** [comment]
What error message are you getting? Can you share your sessionInfo() ? Everything works fine on my end.

**Comment by hvhungoc** [comment]
Thanks for your reply
this bug comes into my message column and looks like: 
"Lo<U+1EA1>t cap ch<U+1EA5>t cho anh em v<U+1EC1>..."
