### ISSUE TITLE
Getting an error with the getPage function where reactions = TRUE

### ISSUE THREAD

**Issue by wsamuelw** [pablobarbera/Rfacebook#88]
The getPage function getPage(Account, fb_oauth, n = 1000, reactions = TRUE) doesn't seem to work properly when reactions = TRUE. I've tried setting the value to FALSE. And, it worked. Then, I was using a separate function getReactions(post=page$id, token=fb_oauth) and hoping that might solve the issue. The error message is below:

Error in data.frame(id = p, likes_count = content$like$summary$total_count,  : 
  arguments imply differing number of rows: 1, 0

Any idea what to look into?

**Comment by wsamuelw** [comment]
I have spent some time trying to figure out what might have caused the issue above. I found that the reaction function doesn't work when likes_count is 0. Not entirely sure why likes_count is 0 when in fact the post has got some likes. It could be a permission issue as well. Just wanted flag and hoping there is a better solution for extracting reactions data.

**Comment by pablobarbera** [comment]
Hi @wsamuelw, can you share an example where you're getting this error? Or can you try running the examples in the getReactions() documentation? Everything works fine with me.

**Comment by wsamuelw** [comment]
I have tested the GetPage function where reactions = T on several pages. The issue seems to be that the GetPage function is returning post IDs that no longer exist. These post IDs could have been deleted by the page admin for various reasons. I can't really provide an example. But, if you try setting n = 5000 or high enough to cover some of the old posts from a celebrity's page, then this seems to occur. My fix has been to do another subset to exclude likes_count = 0.

**Comment by pablobarbera** [comment]
Thanks for the information. I'm keeping this issue open, as I haven't been able to replicate the error and it is thus difficult to fix it on my end. If you come up with a specific example I could look at, that would be great.

**Comment by chitemerere** [comment]
I was getting the same error but turning reactions to FALSE gets rid of the error!!!

**Comment by RobertMyles** [comment]
I'm getting the error in #85, with `callAPI()`:

    page <- "166860353356903"
    token < - xxxx
    query <- paste0('https://graph.facebook.com//v2.8/', page,
                  '?fields=likes.limit(', 500, ').fields(id,name,about, description, likes, link, location)')
    content <- callAPI(query, token)

```
>   content <- callAPI(query, token)
Error in rjson::fromJSON(rawToChar(url.data$content)) : 
     unexpected character '<'
```

Any ideas what's going wrong?

**Comment by pablobarbera** [comment]
Hi @RobertMyles sorry for the slow reply. I just tried this exact code and it works on my end. If you're still having this issue, could you share your sessionInfo() ?

**Comment by kasperwelbers** [comment]
Hi @pablobarbera,

Since the update that added support for different API versions the reactions = TRUE in getPage seems to be broken. The reason seems to be that the default v2.6 in getReactions was removed (replaced by the new 'api' argument). The getPage function contains getReactions, but does not pass on the 'api' argument. 

Cheers

**Comment by ILIG-MESSINA** [comment]
Please i'm facing this same issue when trying the collect data from my Facebook page. Can Someone help please ?

page <- getPage(page="Conrad Clotaire Messina Ayissi", token=fb_oauth, n=200, since="2017/07/07", until="2017/07/11")
