### ISSUE TITLE
Import data from Facebook downloaded Data

### ISSUE THREAD

**Issue by mafr0028** [pablobarbera/Rfacebook#89]
Hey,

since fb API v2.0 has such hard restrictions on friends. Is it of any use to download the data from facebook as explained on the [fb help page](https://www.facebook.com/help/302796099745838) and import it with **Rfacebook**?

I would love to create a nice visual graph, but of my 333 fb-friends only one is being displayed in R - probably because he's the only one, who used the **Graph API Explorer**.

**Comment by pablobarbera** [comment]
Unfortunately, no. Rfacebook doesn't have any function to import data downloaded through this method. I'm actually not sure whether you even get the connections among friends (necessary to build the network) this way. My impression is that you could only download your own data. Sorry.
