### ISSUE TITLE
Getting error each time I try to getPage()

### ISSUE THREAD

**Issue by mkmetko** [pablobarbera/Rfacebook#90]
Every time I call the getPage(), I get one of these two errors:

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failure when receiving data from the peer

I was able to get max n=5, larger numbers caused errors.

Any idea how to fix it?
Thanks!

**Comment by pablobarbera** [comment]
Looks like a problem on your end. Are you connected through a proxy? Can you get a response when you try to do this through the API console [here](https://developers.facebook.com/tools/explorer/) ?
