### ISSUE TITLE
Unable to get all posts

### ISSUE THREAD

**Issue by wsamuelw** [pablobarbera/Rfacebook#91]
I was trying to get all posts since 01/01/2016 for this page.

Account <- 'hillaryclinton'
page_1 <- getPage(Account, fb_oauth, n = 5000, since = '2016/01/01', feed = F, reactions = F)

This got me 1295 posts as of today (05/11/16). Then, I ran a few checks and found that I could potentially miss some posts between 2016-01-01T05:06:13+0000 and 2016-06-03T22:31:11+0000.

So, I thought what happens if do this below by covering a shorter period.

Account <- 'hillaryclinton'
page_1 <- getPage(Account, fb_oauth, n = 5000, since = '2016/01/01', until = '2016/05/01', feed = F, reactions = F)

Interestingly, this got me 42 posts. The first date = 2016-01-01T00:03:15+0000 and the next date = 2016-04-26T00:30:00+0000 which is a little odd. Because, the first date has changed when compared to the first extract and it has now included a post from the 26/04/16 which should have been included in the first extract anyway. 

What could have caused the missing data issue? I am guessing it has something to do with the Facebook API itself. I did also try using a different Facebook App.

**Comment by pbdanny** [comment]
Unable to get all visitor post in public page.
code used.
`p1 <- getGroup(195457950893312,token = myFB_Oauth, 
                 since = "2016-10-28T02:00:00", until = "2016-11-18T06:00:00", n = 50000)`
found posts lost on some days. Anyway, apply same code with narrower post period parameter (like day by day), return 'seemed' correct number of post.

**Comment by pablobarbera** [comment]
Interesting. I think part of the issue could be that the API returns posts based on the time they were last edited. I've done a few tests and that seems to explain the missing posts for me. In any case, the issue appears to be with the API and not with Rfacebook, so I'll close this issue for now.
