### ISSUE TITLE
 "word.frequencies"  not run

### ISSUE THREAD

**Issue by roroba** [pablobarbera/Rfacebook#94]
Hi,

I tried to run:

library(smappR)
Error in library(smappR) : there is no package called ‘smappR’
library(wordcloud)
wordFreq <- word.frequencies(posts$message)

But lamentably R could not find the function: "word.frequencies" 

I did try to use smappr but was imposible

Thanks in advance

**Comment by pablobarbera** [comment]
Hi @roroba, please read the documentation for smappR [here](https://github.com/SMAPPNYU/smappR#a-installing-r-packages). It looks like you need to install smappR first :-)
