### ISSUE TITLE
date_breaks instead on breaks

### ISSUE THREAD

**Issue by yanturgeon** [pablobarbera/Rfacebook#96]
Hi Pablo,

In « Analyzing data from a Facebook page » (on this page https://github.com/pablobarbera/Rfacebook), the code bellow:

`scale_x_date(breaks = "years", labels = date_format("%Y")) + scale_y_log10("Average count per post", 
`
Should be replace by this one :

`scale_x_date(date_breaks = "years", labels = date_format("%Y")) + scale_y_log10("Average count per post", 
`
Happy new year !

**Comment by pablobarbera** [comment]
Good catch! Thanks and happy new year to you as well!
