### ISSUE TITLE
Getting location information from public user profiles

### ISSUE THREAD

**Issue by anandnandita** [pablobarbera/Rfacebook#97]
Hi Pablo,

I have more of a question than an issue! I hope you can share your thoughts on it. I replicated your Humans of New York Facebook page analysis example. I was wondering if there is a way I can get location and gender information for the users (from their public profiles) who liked a post so I can perform gender and geolocation analysis. I read the Graph API and the Rfacebook package documentation and explored Rcurl/rjson packages but was not able to get the desired information. Do you have any thoughts on this?

Thanks!

**Comment by pablobarbera** [comment]
Hi @anandnandita -- Unfortunately this type of information is not available anymore. It used to be the case that you could get some basic information such as gender and country for all Facebook users, but after some changes in the API last year, these variables are no longer accessible through the API. Sorry!
